import * as path from 'path';
import * as fs from 'fs/promises';
import * as YAML from 'yaml';
import {
  MigrationPlan,
  MigrationTarget,
  FileChange,
  WorkspaceAnalysis,
  PackageInfo,
} from './types';

/**
 * Creates migration plans based on analysis and target
 */
export class MigrationPlanner {
  private workspaceRoot: string;

  constructor(workspaceRoot: string) {
    this.workspaceRoot = workspaceRoot;
  }

  /**
   * Create a migration plan for the given target
   */
  async createPlan(
    analysis: WorkspaceAnalysis,
    target: MigrationTarget
  ): Promise<MigrationPlan> {
    if (target === 'keep_current') {
      return {
        target,
        changes: [],
        postMigrationCommands: [],
        summary: {
          filesToCreate: 0,
          filesToModify: 0,
          filesToDelete: 0,
          packagesToMigrate: 0,
        },
      };
    }

    const changes: FileChange[] = [];
    const postMigrationCommands: string[] = [];

    // Step 1: Create or update root pubspec.yaml
    const rootPubspecChange = await this.createRootPubspecChange(analysis);
    changes.push(rootPubspecChange);

    // Step 2: Update each package's pubspec.yaml with resolution: workspace
    for (const pkg of analysis.packages) {
      if (!pkg.hasResolutionWorkspace) {
        const packageChange = await this.createPackageChange(pkg);
        changes.push(packageChange);
      }
    }

    // Step 3: Delete existing lockfiles (they will be replaced by root lockfile)
    for (const pkg of analysis.packages) {
      const lockfilePath = path.join(pkg.path.replace('/pubspec.yaml', ''), 'pubspec.lock');
      const hasLockfile = await this.fileExists(lockfilePath);
      if (hasLockfile) {
        changes.push({
          path: lockfilePath,
          relativePath: path.relative(this.workspaceRoot, lockfilePath),
          type: 'delete',
          description: `Delete ${pkg.name}/pubspec.lock (replaced by root lockfile)`,
        });
      }
    }

    // Step 4: Add Melos if requested
    if (target === 'pub_workspaces_melos') {
      const melosChange = await this.createMelosChange(analysis);
      changes.push(melosChange);
      postMigrationCommands.push('dart pub global activate melos');
      postMigrationCommands.push('melos bootstrap');
    } else {
      postMigrationCommands.push('dart pub get');
    }

    // Calculate summary
    const summary = {
      filesToCreate: changes.filter((c) => c.type === 'create').length,
      filesToModify: changes.filter((c) => c.type === 'modify').length,
      filesToDelete: changes.filter((c) => c.type === 'delete').length,
      packagesToMigrate: analysis.packages.filter((p) => !p.hasResolutionWorkspace).length,
    };

    return {
      target,
      changes,
      postMigrationCommands,
      summary,
    };
  }

  /**
   * Create the root pubspec.yaml change
   */
  private async createRootPubspecChange(analysis: WorkspaceAnalysis): Promise<FileChange> {
    const rootPath = path.join(this.workspaceRoot, 'pubspec.yaml');
    const exists = await this.fileExists(rootPath);

    // Determine workspace name from folder
    const workspaceName = path.basename(this.workspaceRoot).replace(/[^a-z0-9_]/gi, '_');

    // Build workspace entries (relative paths)
    const workspaceEntries = analysis.packages.map((pkg) => pkg.relativePath);

    // Use highest SDK constraint
    const sdkConstraint = this.getHighestSdkConstraint(analysis.packages);

    const newContent = this.generateRootPubspec(workspaceName, sdkConstraint, workspaceEntries);

    if (exists) {
      const originalContent = await fs.readFile(rootPath, 'utf8');
      return {
        path: rootPath,
        relativePath: 'pubspec.yaml',
        type: 'modify',
        originalContent,
        newContent,
        description: 'Update root pubspec.yaml with workspace configuration',
      };
    } else {
      return {
        path: rootPath,
        relativePath: 'pubspec.yaml',
        type: 'create',
        newContent,
        description: 'Create root pubspec.yaml with workspace configuration',
      };
    }
  }

  /**
   * Generate root pubspec.yaml content
   */
  private generateRootPubspec(
    name: string,
    sdkConstraint: string,
    workspaceEntries: string[]
  ): string {
    const doc = new YAML.Document({
      name: name.toLowerCase(),
      publish_to: 'none',
      environment: {
        sdk: sdkConstraint,
      },
      workspace: workspaceEntries.sort(),
    });

    // Add comment at the top
    const content = doc.toString();
    return `# Pubspec Master - Workspace Configuration
# Generated by Pubspec Master VS Code Extension
# https://github.com/moinsen-dev/pubspec-master

${content}`;
  }

  /**
   * Create a package pubspec.yaml change
   */
  private async createPackageChange(pkg: PackageInfo): Promise<FileChange> {
    const originalContent = await fs.readFile(pkg.path, 'utf8');

    // Parse the original YAML
    const doc = YAML.parseDocument(originalContent);

    // Add resolution: workspace after the name field
    const contents = doc.contents as YAML.YAMLMap;
    if (contents && !contents.has('resolution')) {
      // Find the position after 'name' to insert 'resolution'
      const nameIndex = contents.items.findIndex(
        (item) => (item.key as YAML.Scalar)?.value === 'name'
      );

      if (nameIndex !== -1) {
        // Insert after name
        const resolutionPair = doc.createPair('resolution', 'workspace');
        contents.items.splice(nameIndex + 1, 0, resolutionPair);
      } else {
        // If no name found (shouldn't happen), add at the beginning
        contents.set('resolution', 'workspace');
      }
    }

    const newContent = doc.toString();

    return {
      path: pkg.path,
      relativePath: path.relative(this.workspaceRoot, pkg.path),
      type: 'modify',
      originalContent,
      newContent,
      description: `Add resolution: workspace to ${pkg.name}`,
    };
  }

  /**
   * Create melos.yaml change
   */
  private async createMelosChange(analysis: WorkspaceAnalysis): Promise<FileChange> {
    const melosPath = path.join(this.workspaceRoot, 'melos.yaml');
    const exists = await this.fileExists(melosPath);

    const workspaceName = path.basename(this.workspaceRoot).replace(/[^a-z0-9_]/gi, '_');

    const newContent = this.generateMelosConfig(workspaceName, analysis.packages);

    if (exists) {
      const originalContent = await fs.readFile(melosPath, 'utf8');
      return {
        path: melosPath,
        relativePath: 'melos.yaml',
        type: 'modify',
        originalContent,
        newContent,
        description: 'Update melos.yaml configuration',
      };
    } else {
      return {
        path: melosPath,
        relativePath: 'melos.yaml',
        type: 'create',
        newContent,
        description: 'Create melos.yaml configuration',
      };
    }
  }

  /**
   * Generate melos.yaml content
   */
  private generateMelosConfig(name: string, packages: PackageInfo[]): string {
    // Group packages by type
    const apps = packages.filter((p) => p.type === 'flutter_app');
    const plugins = packages.filter((p) => p.type === 'flutter_plugin');
    const dartPackages = packages.filter((p) => p.type === 'dart_package');

    const config: Record<string, unknown> = {
      name: name.toLowerCase(),
      packages: ['**'],
      scripts: {
        analyze: {
          run: 'dart analyze .',
          description: 'Analyze all packages',
        },
        test: {
          run: 'melos run test --no-select',
          description: 'Run tests in all packages',
        },
        'test:select': {
          run: 'flutter test',
          exec: {
            concurrency: 1,
          },
          packageFilters: {
            dirExists: 'test',
          },
          description: 'Run tests in selected packages',
        },
        format: {
          run: 'dart format .',
          description: 'Format all Dart code',
        },
        clean: {
          run: 'flutter clean',
          exec: {
            concurrency: 5,
          },
          description: 'Clean all packages',
        },
      },
    };

    // Add command filter groups if there are multiple package types
    if (apps.length > 0 || plugins.length > 0 || dartPackages.length > 0) {
      const commandFilters: Record<string, unknown> = {};

      if (apps.length > 0) {
        commandFilters.apps = {
          packageFilters: {
            flutter: true,
            dependsOn: 'flutter',
          },
        };
      }

      if (plugins.length > 0) {
        commandFilters.plugins = {
          packageFilters: {
            flutter: true,
          },
        };
      }

      config.command = {
        bootstrap: {
          usePubspecOverrides: true,
        },
        ...commandFilters,
      };
    }

    const doc = new YAML.Document(config);
    return `# Melos Configuration
# Generated by Pubspec Master VS Code Extension
# https://melos.invertase.dev/

${doc.toString()}`;
  }

  /**
   * Get the highest SDK constraint from packages
   */
  private getHighestSdkConstraint(packages: PackageInfo[]): string {
    if (packages.length === 0) {return '^3.6.0';}

    let highest = '0.0.0';

    for (const pkg of packages) {
      const version = this.extractVersion(pkg.sdkConstraint || '>=3.6.0');
      if (this.compareVersions(version, highest) > 0) {
        highest = version;
      }
    }

    return `^${highest}`;
  }

  /**
   * Extract version from constraint
   */
  private extractVersion(constraint: string): string {
    const match = constraint.match(/(\d+\.\d+\.\d+)/);
    return match ? match[1] : '3.6.0';
  }

  /**
   * Compare versions
   */
  private compareVersions(a: string, b: string): number {
    const partsA = a.split('.').map(Number);
    const partsB = b.split('.').map(Number);

    for (let i = 0; i < 3; i++) {
      const diff = (partsA[i] || 0) - (partsB[i] || 0);
      if (diff !== 0) {return diff;}
    }
    return 0;
  }

  /**
   * Check if file exists
   */
  private async fileExists(filePath: string): Promise<boolean> {
    try {
      await fs.access(filePath);
      return true;
    } catch {
      return false;
    }
  }
}
